site_name: FutureSoot
#site_url: https://example.com/
repo_url: https://github.com/secure-software-engineering/soot-reloaded/

nav:
    - Home: index.md
    - Installation: installation.md
    - Getting started: getting-started.md
    - Call Graph Construction: call-graph-construction.md
    - Jimple: jimple.md
    - Advanced Topics: advanced-topics.md
#    - Analyses: analyses.md

#  - About: about.md

theme:
  name: material


plugins:
  - tooltips
  - search
  - include:
      src_path: 'examples/src/test/java/de/upb/swt/soot/examples'

extra_css:
  - css/hint.min.css

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      use_pygments: true
      extend_pygments_lang:
        - name: jimple
          lang: lspserver
          options:
            filetype: jimple
            # the path of the jimplelsp.jar needs to be the same as in the gh-pages.yml workflow
            lspcommand: "java -jar ./jimplelsp.jar"

  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - pymdownx.tabbed:
      alternate_style: true

